### ISSUE TITLE
“Uengine检测CPU是否支持运行”功能无法使用。

### ISSUE THREAD

**Issue by BailPlus** [gfdgd-xi/uengine-runner#10]
“Uengine检测CPU是否支持运行”功能无法使用。必现问题。建议修改对应源代码的`simplenet.cpp`路径。
![image](https://user-images.githubusercontent.com/34512765/187421241-cd00f628-f489-4f31-a45f-4d226c29cbfd.png)

**Comment by BailPlus** [comment]
`zll`不是我的用户名

**Comment by gfdgd-xi** [comment]
我这里是正常的（Deepin 20.6），在 UOS 上的问题？我找时间在 UOS 上再测试看看
![image](https://user-images.githubusercontent.com/73065138/187426211-09b834e6-32eb-45ec-8e5c-08a6937899c6.png)

**Comment by gfdgd-xi** [comment]
这是您自己编译的？

**Comment by BailPlus** [comment]
我的也是deepin，20.7

**Comment by BailPlus** [comment]
应该是我的uengine的问题。
我分析你`uengine-runner.py`第646行，终端执行有关命令后如下输出：
```
bail@Bail:~/Documents/git/uengine-runner$ uengine check-features
[ 2022-08-30 13:06:56] [main.cpp:589@open] open failed: 13 Permission denied
[WRN] /home/zll/src/uengine-rel/hw_anbox/ubox-base/simplenet.cpp:181 connect(mSocket, (struct sockaddr *)&addr, len) result(-1) errno(2) No such file or directory
Start uengine service socket error.
Your computer's CPU does meet all requirements to run UEngine
bail@Bail:~/Documents/git/uengine-runner$ 
```

**Comment by gfdgd-xi** [comment]
> 应该是我的uengine的问题。 我分析你`kbox/main.py`第646行，终端执行有关命令后如下输出：
> 
> ```
> bail@Bail:~/Documents/git/uengine-runner$ uengine check-features
> [ 2022-08-30 13:06:56] [main.cpp:589@open] open failed: 13 Permission denied
> [WRN] /home/zll/src/uengine-rel/hw_anbox/ubox-base/simplenet.cpp:181 connect(mSocket, (struct sockaddr *)&addr, len) result(-1) errno(2) No such file or directory
> Start uengine service socket error.
> Your computer's CPU does meet all requirements to run UEngine
> bail@Bail:~/Documents/git/uengine-runner$ 
> ```
> 
> 和在uengine-runner里显示的消息一样。 或许我找错反馈问题的地方了(doge)

应该是找错地方了（doge）但这个东西不是很影响使用（doge）

**Comment by BailPlus** [comment]
好的，谢谢
