### ISSUE TITLE
添加UEngine应用快捷方式出现问题

### ISSUE THREAD

**Issue by BailPlus** [gfdgd-xi/uengine-runner#12]
![image](https://user-images.githubusercontent.com/34512765/189476979-0ef0654c-6fc2-4eea-97bb-679d55002e5d.png)
如图，“添加指定的uengine快捷方式”功能中，点击“保存”按钮后发生的错误。必现问题。
可能原因：改用PyQt5后对应的代码没有进行相应的修改。
改进建议：将对应的获取文本框文本的方法改为PyQt5给出的方法。

**Comment by gfdgd-xi** [comment]
已修复
