### ISSUE TITLE
该模拟器支持需要网络的应用吗

### ISSUE THREAD

**Issue by ckf104** [gfdgd-xi/uengine-runner#16]
我的OS是deepin 20.8，尝试在deepin的应用商店中安装了uengine-runner 2.0.0，然后运行uengine-runner，安装了taptap应用，运行taptap却显示数据加载失败（我猜想是没有网络造成的？）
设置中无线与网络模块也只看到蓝牙，没有网络连接相关的设置？

**Comment by rain-gfd** [comment]
试一下将 deepin 内核降到 5.15，5.18 好像不能联网
