### ISSUE TITLE
该应用未正常初始化,请稍后再打开或重新安装

### ISSUE THREAD

**Issue by SheplX** [gfdgd-xi/uengine-runner#9]
hi, tnx alot for this great work, i just getting this msg with several apps, so can u plz help me how to fix it ? tnx
![Screenshot_20220714134734](https://user-images.githubusercontent.com/93225575/178975933-e426b5e3-9bae-443a-9d5e-f6f289f48a7a.png)

**Comment by gfdgd-xi** [comment]
First. You're UEngine(Android Virtual Machine) don't install well, you can try to see your CPU able run with SSL 4.2
Second. Maybe Android program don't install, you can try to install Android Program again or install other Android program.

**Comment by gfdgd-xi** [comment]
And I try to install this app, it can open with launcher.
![图片](https://user-images.githubusercontent.com/73065138/181862409-8dfa0858-2bd9-4c55-b667-21be9a0fbc1d.png)

**Comment by SheplX** [comment]
> And I try to install this app, it can open with launcher. ![图片](https://user-images.githubusercontent.com/73065138/181862409-8dfa0858-2bd9-4c55-b667-21be9a0fbc1d.png)

if I am wrong can u show me the full steps of the installation steps?
sry I don't understand anything cuz i don't speak Chinese language
